/**
 * Fetch the typeface this app ships and write the CSS that declares it: `pnpm fonts:import`.
 * Served from here rather than Google's CDN so that opening a timetable tells nobody (PRIVACY.md).
 * Latin subset only; Galician and Spanish fit inside it. Commit src/fonts/*.woff2 and src/fonts.css.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { at } from './lib';

const OUT = at('src', 'fonts');
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36';
const get = (url: string) => fetch(url, { headers: { 'User-Agent': UA } });

// Google serves nothing heavier than 700 for these families: the app's `font-black` renders
// as the bold face because there is no black one.
const FAMILIES: [string, string, number[]][] = [
  ['Atkinson Hyperlegible Next', 'next', [400, 500, 600, 700]],
  ['Atkinson Hyperlegible Mono', 'mono', [400, 500, 600, 700]],
];

const HEADER = `/* Atkinson Hyperlegible Next and Mono, Braille Institute of America, SIL Open Font
   License 1.1 — the licence text is in fonts/OFL.txt beside these files.

   Served from here rather than from Google's CDN, so that opening a bus timetable does
   not tell Google you did. Not a speed decision: browsers partitioned their cache years
   ago, and either way only the faces a screen uses are downloaded. See PRIVACY.md.

   Latin subset only. Generated by tools/importFonts.ts, not written by hand. */
`;

mkdirSync(OUT, { recursive: true });

const faces: { family: string; weight: string; file: string; range: string }[] = [];
// One file per distinct set of bytes: these are variable fonts, so Google's four faces point
// at one file. Keyed by content, so real static weights would still all be written.
const written = new Map<string, string>();
let total = 0;

for (const [family, slug, weights] of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weights.join(';')}&display=swap`;
  const css = await get(url).then((r) => r.text());

  for (const block of css.matchAll(/@font-face \{([\s\S]*?)\}/g)) {
    const body = block[1];
    // The latin block, identified by the range itself rather than by a comment Google may drop.
    if (!/U\+0000-00FF/.test(body)) continue;
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
    const src = body.match(/url\((https:\/\/[^)]+)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    if (!weight || !src || !range) throw new Error(`could not read a face of ${family}`);

    const downloaded = await get(src).then((r) => r.arrayBuffer());
    const bytes = new Uint8Array(downloaded);
    const digest = createHash('sha256').update(bytes).digest('hex').slice(0, 8);

    let file = written.get(digest);
    if (!file) {
      // Named by content, not by weight: four faces sharing one file are not `next-700`.
      file = `${slug}-${digest}.woff2`;
      writeFileSync(join(OUT, file), bytes);
      written.set(digest, file);
      total += bytes.length;
      console.log(`  ${file.padEnd(20)} ${(bytes.length / 1024).toFixed(0).padStart(3)} KB`);
    }
    faces.push({ family, weight, file, range });
  }
}

if (!faces.length) throw new Error('no latin faces came back; the upstream CSS changed shape');

const declarations = faces.map(
  (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('./fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`,
);

writeFileSync(at('src', 'fonts.css'), `${HEADER}\n${declarations.join('\n')}\n`);
console.log(`\n${faces.length} faces over ${written.size} files, ${(total / 1024).toFixed(0)} KB`);
console.log('wrote src/fonts.css — remember OFL.txt travels with the files');
