/**
 * The shipped network and the fares.
 *
 * stops.json and lines.json are generated by tools/importOfficialData.ts +
 * tools/buildDataset.ts from the operator's published network. Do not hand-edit them.
 */
import rawStops from './stops.json';
import rawLines from './lines.json';
import { BusStop, BusLine } from '../types';

export const LUGO_CENTER: [number, number] = [43.0125, -7.5558];

export const BUS_STOPS: BusStop[] = rawStops as BusStop[];
export const BUS_LINES: BusLine[] = (rawLines as unknown as BusLine[]).map((line) => ({
  ...line,
  // Placeholders until data/routeGeometry.ts hydrates them on the first map view.
  directions: line.directions.map((d) => ({ ...d, pathCoordinates: [], stopPathIndex: [] })),
}));

const STOP_BY_ID = new Map(BUS_STOPS.map((s) => [s.id, s]));
const LINE_BY_ID = new Map(BUS_LINES.map((l) => [l.id, l]));

export const stopById = (id: string): BusStop | undefined => STOP_BY_ID.get(id);
export const lineById = (id: string): BusLine | undefined => LINE_BY_ID.get(id);
/** The name behind a stop id, or the id itself when the dataset does not know it. */
export const stopName = (id: string): string => STOP_BY_ID.get(id)?.name ?? id;

/**
 * The code printed on the pole, or null. Only 271 of the 417 stops have one; for the rest
 * an internal number that appears nowhere in the street is worse than nothing.
 */
export const poleCode = (stop: BusStop): string | null => stop.officialToken || null;

/**
 * Fares, exactly as buslugo.com/tarifas publishes them — never inferred. One "bono
 * social" of 0,31 € covers youth, university, pensioner, unemployed and disability.
 */
export const FARES = {
  singleTicket: 0.64,
  citizenCard: 0.45,
  socialCard: 0.31,
  transfer: 0,
  freeTransferWindowMinutes: 75,
  /** Urban trip with the Galician metropolitan card: the "0 saltos (**)" row at tmg.xunta.gal. */
  metropolitanCardUrban: 0.45,
  metropolitanTransferMinutes: 60,
} as const;

export const formatEuros = (amount: number): string => `${amount.toFixed(2).replace('.', ',')} €`;

const BUSLUGO = 'buslugo.com/tarifas';
const BUSLUGO_URL = 'https://buslugo.com/tarifas';

/**
 * The four fares, and the facts about them that are not language: the price, computed
 * from FARES so there is one number, and where to verify it. The words are in
 * `t.fares.cards`; `minutes` is the figure the copy interpolates where it has one.
 */
export const FARE_CARDS = [
  { id: 'single', price: formatEuros(FARES.singleTicket), source: BUSLUGO, sourceUrl: BUSLUGO_URL },
  {
    id: 'citizenCard',
    price: formatEuros(FARES.citizenCard),
    minutes: FARES.freeTransferWindowMinutes,
    source: BUSLUGO,
    sourceUrl: BUSLUGO_URL,
  },
  { id: 'socialCard', price: formatEuros(FARES.socialCard), source: BUSLUGO, sourceUrl: BUSLUGO_URL },
  {
    id: 'tmg',
    price: formatEuros(FARES.metropolitanCardUrban),
    minutes: FARES.metropolitanTransferMinutes,
    source: 'tmg.xunta.gal/area-de-lugo',
    sourceUrl: 'https://tmg.xunta.gal/area-de-lugo',
  },
] as const;

export const FARE_INFO = {
  singleTicket: formatEuros(FARES.singleTicket),
  bonobusTicket: formatEuros(FARES.citizenCard),
  socialTicket: formatEuros(FARES.socialCard),
  transfers: `Transbordo gratuíto nos primeiros ${FARES.freeTransferWindowMinutes} minutos coa Tarxeta Cidadá`,
  metropolitanCard: 'A Tarxeta do Transporte Metropolitano de Galicia (TMG) tamén é válida na rede urbana de Lugo',
  source: BUSLUGO_URL,
};
