/**
 * Transit data + fares.
 *
 * stops.json and lines.json are generated by tools/importOfficialData.ts +
 * tools/buildDataset.ts from the operator's published network, with every itinerary
 * snapped to the real street network. Do not hand-edit them.
 */

import type { Lang } from '../i18n';
import rawStops from './stops.json';
import rawLines from './lines.json';
import { BusStop, BusLine } from '../types';

export const LUGO_CENTER: [number, number] = [43.0125, -7.5558];

export const BUS_STOPS: BusStop[] = rawStops as BusStop[];
export const BUS_LINES: BusLine[] = (rawLines as unknown as BusLine[]).map((line) => ({
  ...line,
  // Placeholders until data/routeGeometry.ts hydrates them on the first map view.
  directions: line.directions.map((d) => ({ ...d, pathCoordinates: [], stopPathIndex: [] })),
}));

/**
 * The code actually printed on the pole, or null. Only 271 of the 417 stops have one
 * (the ones with a live panel); for the rest the app was showing an internal number
 * that appears nowhere in the street, which is worse than showing nothing.
 */
export const poleCode = (stop: BusStop): string | null => stop.officialToken || null;

/**
 * Fares, exactly as buslugo.com/tarifas publishes them.
 *
 * The previous table invented a 0,19 € pensioner fare. The operator has a single
 * "bono social" of 0,31 € covering youth, university, pensioner, unemployed and
 * disability, and both transfer types are free with the Tarxeta Cidadá.
 */
export const FARES = {
  singleTicket: 0.64,
  citizenCard: 0.45,
  socialCard: 0.31,
  transfer: 0,
  freeTransferWindowMinutes: 75,
  /**
   * Urban trip with the Galician metropolitan card. tmg.xunta.gal publishes it as the
   * "0 saltos (**)" row of the Lugo area table, where (**) means a trip on the city's
   * own network. Same price as the municipal bono.
   */
  metropolitanCardUrban: 0.45,
  /** Free transfer window for a 0-salto trip with the TMG. */
  metropolitanTransferMinutes: 60,
} as const;

const formatEuros = (amount: number): string => `${amount.toFixed(2).replace('.', ',')} €`;

interface FareCardItem {
  badge: string;
  title: string;
  /** Empty when the operator publishes no price for it — see the TMG card. */
  price: string;
  subtitle: string;
  details: string;
  /** Where this came from, so nothing on this screen is unattributable. */
  source: string;
  sourceUrl: string;
}

const BUSLUGO = 'buslugo.com/tarifas';
const BUSLUGO_URL = 'https://buslugo.com/tarifas';
const TMG_URL = 'https://tmg.xunta.gal/area-de-lugo';

/**
 * Fare cards, in every interface language.
 *
 * Typed as a full Record so a new language cannot be added without its fares: the
 * lookup used to be `FARES_LIST[lang] || FARES_LIST.gl`, which quietly served Galician
 * prices to an English reader rather than failing loudly.
 */
export const FARES_LIST: Record<Lang, FareCardItem[]> = {
  gl: [
    {
      badge: 'Xeral',
      title: 'Billete ordinario',
      price: formatEuros(FARES.singleTicket),
      subtitle: 'Pago a bordo',
      details: 'Válido para unha viaxe en calquera liña da rede urbana de Lugo.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Tarxeta Cidadá',
      title: 'Bono ordinario',
      price: formatEuros(FARES.citizenCard),
      subtitle: `Transbordo gratuíto (${FARES.freeTransferWindowMinutes} min)`,
      details: 'Require ter a Tarxeta Cidadá do Concello de Lugo.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Tarxeta Cidadá',
      title: 'Bono social',
      price: formatEuros(FARES.socialCard),
      subtitle: 'Mocidade, universitario, pensionista, desemprego e discapacidade',
      details: 'Transbordo social tamén gratuíto. Consulta as condicións no teléfono 010.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Xunta de Galicia',
      title: 'Tarxeta do transporte público de Galicia (TMG)',
      price: formatEuros(FARES.metropolitanCardUrban),
      subtitle: 'Válida na rede urbana de Lugo',
      details: `Se chegas nun bus metropolitano, o urbano vai incluído dentro dos ${FARES.metropolitanTransferMinutes} min seguintes sen pagar de novo. Máis de 41 viaxes metropolitanas ao mes devolven o 15% do gasto.`,
      source: 'tmg.xunta.gal/area-de-lugo',
      sourceUrl: TMG_URL,
    },
  ],
  es: [
    {
      badge: 'General',
      title: 'Billete ordinario',
      price: formatEuros(FARES.singleTicket),
      subtitle: 'Pago a bordo',
      details: 'Válido para un viaje en cualquier línea de la red urbana de Lugo.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Tarjeta Ciudadana',
      title: 'Bono ordinario',
      price: formatEuros(FARES.citizenCard),
      subtitle: `Transbordo gratuito (${FARES.freeTransferWindowMinutes} min)`,
      details: 'Requiere tener la Tarjeta Ciudadana del Ayuntamiento de Lugo.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Tarjeta Ciudadana',
      title: 'Bono social',
      price: formatEuros(FARES.socialCard),
      subtitle: 'Juvenil, universitario, pensionista, desempleo y discapacidad',
      details: 'El transbordo social también es gratuito. Consulta las condiciones en el teléfono 010.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Xunta de Galicia',
      title: 'Tarjeta del transporte público de Galicia (TMG)',
      price: formatEuros(FARES.metropolitanCardUrban),
      subtitle: 'Válida en la red urbana de Lugo',
      details: `Si llegas en un bus metropolitano, el urbano va incluido dentro de los ${FARES.metropolitanTransferMinutes} min siguientes sin volver a pagar. Más de 41 viajes metropolitanos al mes devuelven el 15% del gasto.`,
      source: 'tmg.xunta.gal/area-de-lugo',
      sourceUrl: TMG_URL,
    },
  ],
  en: [
    {
      badge: 'Standard',
      title: 'Single ticket',
      price: formatEuros(FARES.singleTicket),
      subtitle: 'Paid on board',
      details: 'Valid for one trip on any line of the Lugo city network.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Tarxeta Cidadá',
      title: 'Standard travel card fare',
      price: formatEuros(FARES.citizenCard),
      subtitle: `Free transfer (${FARES.freeTransferWindowMinutes} min)`,
      details: 'Requires the Tarxeta Cidadá issued by Lugo city council.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Tarxeta Cidadá',
      title: 'Concession fare',
      price: formatEuros(FARES.socialCard),
      subtitle: 'Young people, students, pensioners, unemployed and disabled passengers',
      details: 'Transfers are free on this fare too. Ask about eligibility on 010.',
      source: BUSLUGO,
      sourceUrl: BUSLUGO_URL,
    },
    {
      badge: 'Xunta de Galicia',
      title: 'Galician public transport card (TMG)',
      price: formatEuros(FARES.metropolitanCardUrban),
      subtitle: 'Valid on the Lugo city network',
      details: `If you arrive on a regional bus, the city bus is included for the next ${FARES.metropolitanTransferMinutes} min at no extra charge. More than 41 regional trips a month earns 15% of the spend back.`,
      source: 'tmg.xunta.gal/area-de-lugo',
      sourceUrl: TMG_URL,
    },
  ],
};

export const FARE_INFO = {
  singleTicket: formatEuros(FARES.singleTicket),
  bonobusTicket: formatEuros(FARES.citizenCard),
  socialTicket: formatEuros(FARES.socialCard),
  transfers: `Transbordo gratuíto nos primeiros ${FARES.freeTransferWindowMinutes} minutos coa Tarxeta Cidadá`,
  metropolitanCard: 'A Tarxeta do transporte público de Galicia (TMG) tamén é válida na rede urbana de Lugo',
  source: 'https://buslugo.com/tarifas',
};
