/**
 * Transit data + fares.
 *
 * stops.json and lines.json are generated by tools/importOfficialData.ts +
 * tools/buildDataset.ts from the operator's published network, with every itinerary
 * snapped to the real street network. Do not hand-edit them.
 */

import type { Lang } from '../i18n';
import rawStops from './stops.json';
import rawLines from './lines.json';
import { BusStop, BusLine } from '../types';

export const LUGO_CENTER: [number, number] = [43.0125, -7.5558];

export const BUS_STOPS: BusStop[] = rawStops as BusStop[];
export const BUS_LINES: BusLine[] = (rawLines as unknown as BusLine[]).map((line) => ({
  ...line,
  // Placeholders until data/routeGeometry.ts hydrates them on the first map view.
  directions: line.directions.map((d) => ({ ...d, pathCoordinates: [], stopPathIndex: [] })),
}));

/**
 * The code actually printed on the pole, or null. Only 271 of the 417 stops have one
 * (the ones with a live panel); for the rest the app was showing an internal number
 * that appears nowhere in the street, which is worse than showing nothing.
 */
export const poleCode = (stop: BusStop): string | null => stop.officialToken || null;

/**
 * Fares, exactly as buslugo.com/tarifas publishes them.
 *
 * The previous table invented a 0,19 € pensioner fare. The operator has a single
 * "bono social" of 0,31 € covering youth, university, pensioner, unemployed and
 * disability, and both transfer types are free with the Tarxeta Cidadá.
 */
export const FARES = {
  singleTicket: 0.64,
  citizenCard: 0.45,
  socialCard: 0.31,
  transfer: 0,
  freeTransferWindowMinutes: 75,
  /**
   * Urban trip with the Galician metropolitan card. tmg.xunta.gal publishes it as the
   * "0 saltos (**)" row of the Lugo area table, where (**) means a trip on the city's
   * own network. Same price as the municipal bono.
   */
  metropolitanCardUrban: 0.45,
  /** Free transfer window for a 0-salto trip with the TMG. */
  metropolitanTransferMinutes: 60,
} as const;

const formatEuros = (amount: number): string => `${amount.toFixed(2).replace('.', ',')} €`;

const BUSLUGO = 'buslugo.com/tarifas';
const BUSLUGO_URL = 'https://buslugo.com/tarifas';
const TMG_URL = 'https://tmg.xunta.gal/area-de-lugo';

/**
 * The four fares, and the facts about them that are not language.
 *
 * This was `FARES_LIST: Record<Lang, FareCardItem[]>` — the same four cards written out
 * three times, 116 lines, with the price and the source repeated in each copy and the
 * prose sitting in `src/data/` rather than in the dictionaries. Thirty-six strings of
 * interface text lived outside the translation system, where the check that catches
 * Galician typed into a view does not look.
 *
 * What is left here is what does not change with the reader: the price, computed from
 * FARES so there is one number and not twelve, and where to go and verify it. The words
 * are in `t.fares.cards`.
 *
 * `minutes` is the figure the copy interpolates, where it has one. Passing it from here
 * keeps the dictionaries free of any import from the dataset.
 */
export const FARE_CARDS = [
  {
    id: 'single',
    price: formatEuros(FARES.singleTicket),
    source: BUSLUGO,
    sourceUrl: BUSLUGO_URL,
  },
  {
    id: 'citizenCard',
    price: formatEuros(FARES.citizenCard),
    minutes: FARES.freeTransferWindowMinutes,
    source: BUSLUGO,
    sourceUrl: BUSLUGO_URL,
  },
  {
    id: 'socialCard',
    price: formatEuros(FARES.socialCard),
    source: BUSLUGO,
    sourceUrl: BUSLUGO_URL,
  },
  {
    id: 'tmg',
    price: formatEuros(FARES.metropolitanCardUrban),
    minutes: FARES.metropolitanTransferMinutes,
    source: 'tmg.xunta.gal/area-de-lugo',
    sourceUrl: TMG_URL,
  },
] as const;

export const FARE_INFO = {
  singleTicket: formatEuros(FARES.singleTicket),
  bonobusTicket: formatEuros(FARES.citizenCard),
  socialTicket: formatEuros(FARES.socialCard),
  transfers: `Transbordo gratuíto nos primeiros ${FARES.freeTransferWindowMinutes} minutos coa Tarxeta Cidadá`,
  metropolitanCard: 'A Tarxeta do transporte público de Galicia (TMG) tamén é válida na rede urbana de Lugo',
  source: 'https://buslugo.com/tarifas',
};
